openapi: 3.0.0
info:
  title: Admin Authentication API
  version: 1.0.0
  description: API for admin authentication operations
  contact:
    name: API Support
    email: support@example.com

servers:
  - url: http://localhost:3000/api/v1
    description: Development server

paths:
  /admin/auth/login:
    post:
      summary: Admin login
      tags: [Admin Authentication]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
              properties:
                email:
                  type: string
                  format: email
                  example: admin@example.com
                password:
                  type: string
                  format: password
                  example: Admin123!
      responses:
        200:
          description: Login successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: Admin login successful
                  data:
                    type: object
                    properties:
                      token:
                        type: string
                        example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
                      user:
                        type: object
                        properties:
                          id:
                            type: integer
                            example: 1
                          name:
                            type: string
                            example: Administrator
                          email:
                            type: string
                            example: admin@example.com
                          role_id:
                            type: integer
                            example: 1
        401:
          description: Invalid credentials
        403:
          description: Admin access required

  /admin/auth/forgot-password:
    post:
      summary: Request admin password reset
      tags: [Admin Authentication]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
              properties:
                email:
                  type: string
                  format: email
                  example: admin@example.com
      responses:
        200:
          description: Reset email sent
        500:
          description: Server error

  /admin/auth/reset-password/{token}:
    post:
      summary: Reset admin password
      tags: [Admin Authentication]
      parameters:
        - name: token
          in: path
          required: true
          schema:
            type: string
          description: Reset token from email
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - password
              properties:
                password:
                  type: string
                  format: password
                  example: NewAdmin123!
      responses:
        200:
          description: Password reset successful
        400:
          description: Invalid or expired token

  /admin/auth/me:
    get:
      summary: Get current admin user profile
      tags: [Admin]
      security:
        - bearerAuth: []
      responses:
        200:
          description: User profile retrieved
        401:
          description: Unauthorized

  /admin/auth/logout:
    post:
      summary: Admin logout
      tags: [Admin Authentication]
      security:
        - bearerAuth: []
      responses:
        200:
          description: Logout successful

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT