openapi: 3.0.0
info:
  title: Driver Management API
  description: API for managing drivers, their documents, and license information
  version: 1.0.0
servers:
  - url: http://localhost:3000/api
    description: Development server

tags:
  - name: Drivers
    description: Driver management endpoints

paths:
  /drivers:
    post:
      tags: [Drivers]
      summary: Create a new driver
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                user_id:
                  type: integer
                  example: 1
                  description: ID of the user who owns this driver record
                name:
                  type: string
                  example: "John Doe"
                  description: Full name of the driver
                license_number:
                  type: string
                  example: "DL1234567890"
                  description: Driver's license number
                license_expiry:
                  type: string
                  format: date
                  example: "2025-12-31"
                  description: License expiry date
                contact_number:
                  type: string
                  example: "+1234567890"
                  description: Driver's contact number
                address:
                  type: string
                  example: "123 Main Street, City, State"
                  description: Driver's residential address
                emergency_contact_number:
                  type: string
                  example: "+1987654321"
                  description: Emergency contact number
                whatsapp_number:
                  type: string
                  example: "+1234567890"
                  description: WhatsApp contact number
                driving_skill:
                  type: string
                  enum: [beginner, intermediate, expert]
                  example: "expert"
                  description: Driver's skill level
                notes:
                  type: string
                  example: "Experienced driver with 10 years of experience"
                  description: Additional notes about the driver
                id_proof:
                  type: string
                  format: binary
                  description: ID proof document (image)
                driver_photo:
                  type: string
                  format: binary
                  description: Driver's photograph (image)
      responses:
        201:
          description: Driver created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: "Driver created successfully"
                  data:
                    type: object
                    properties:
                      driverId:
                        type: integer
                        example: 1
        400:
          description: Bad request - validation error
        401:
          description: Unauthorized
        500:
          description: Internal server error

    get:
      tags: [Drivers]
      summary: Get all drivers with pagination
      parameters:
        - name: user_id
          in: query
          required: false
          schema:
            type: integer
            example: 1
        - name: search
          in: query
          required: false
          schema:
            type: string
            example: "john"
        - name: page
          in: query
          required: false
          schema:
            type: integer
            example: 1
        - name: limit
          in: query
          required: false
          schema:
            type: integer
            example: 10
        - name: sort_by
          in: query
          required: false
          schema:
            type: string
            enum: [id, name, license_number, created_at, updated_at]
            example: "id"
        - name: sort_order
          in: query
          required: false
          schema:
            type: string
            enum: [ASC, DESC]
            example: "DESC"
      responses:
        200:
          description: List of drivers retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  data:
                    type: object
                    properties:
                      drivers:
                        type: array
                        items:
                          type: object
                          properties:
                            id:
                              type: integer
                              example: 1
                            user_id:
                              type: integer
                              example: 1
                            user_name:
                              type: string
                              example: "Admin User"
                            name:
                              type: string
                              example: "John Doe"
                            license_number:
                              type: string
                              example: "DL1234567890"
                            license_expiry:
                              type: string
                              format: date
                              example: "2025-12-31"
                            contact_number:
                              type: string
                              example: "+1234567890"
                            id_proof:
                              type: string
                              example: "https://bucket.s3.region.amazonaws.com/travel/driver/id-proof/image.jpg"
                            driver_photo:
                              type: string
                              example: "https://bucket.s3.region.amazonaws.com/travel/driver/photos/photo.jpg"
                            address:
                              type: string
                              example: "123 Main Street, City, State"
                            emergency_contact_number:
                              type: string
                              example: "+1987654321"
                            whatsapp_number:
                              type: string
                              example: "+1234567890"
                            driving_skill:
                              type: string
                              example: "expert"
                            notes:
                              type: string
                              example: "Experienced driver with 10 years of experience"
                            created_at:
                              type: string
                              format: date-time
                            updated_at:
                              type: string
                              format: date-time
                      pagination:
                        type: object
                        properties:
                          current_page:
                            type: integer
                            example: 1
                          total_pages:
                            type: integer
                            example: 5
                          total_count:
                            type: integer
                            example: 50
                          has_next_page:
                            type: boolean
                            example: true
                          has_prev_page:
                            type: boolean
                            example: false
                          next_page:
                            type: integer
                            nullable: true
                            example: 2
                          prev_page:
                            type: integer
                            nullable: true
                            example: null
                          limit:
                            type: integer
                            example: 10
        401:
          description: Unauthorized
        500:
          description: Internal server error

  /drivers/all/list:
    get:
      tags: [Drivers]
      summary: Get all drivers list (without pagination)
      responses:
        200:
          description: List of all drivers retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  data:
                    type: object
                    properties:
                      drivers:
                        type: array
                      count:
                        type: integer
                        example: 25
        401:
          description: Unauthorized
        500:
          description: Internal server error

  /drivers/{id}:
    get:
      tags: [Drivers]
      summary: Get a specific driver by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            example: 1
      responses:
        200:
          description: Driver details retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  data:
                    type: object
                    properties:
        404:
          description: Driver not found
        401:
          description: Unauthorized
        500:
          description: Internal server error

    put:
      tags: [Drivers]
      summary: Update a driver
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            example: 1
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: "John Doe Updated"
                license_number:
                  type: string
                  example: "DL1234567890"
                license_expiry:
                  type: string
                  format: date
                  example: "2026-12-31"
                contact_number:
                  type: string
                  example: "+1234567890"
                address:
                  type: string
                  example: "456 Updated Street, City, State"
                emergency_contact_number:
                  type: string
                  example: "+1987654321"
                whatsapp_number:
                  type: string
                  example: "+1234567890"
                driving_skill:
                  type: string
                  enum: [beginner, intermediate, expert]
                  example: "expert"
                notes:
                  type: string
                  example: "Updated notes about the driver"
                id_proof:
                  type: string
                  format: binary
                driver_photo:
                  type: string
                  format: binary
      responses:
        200:
          description: Driver updated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: "Driver updated successfully"
        400:
          description: Bad request - validation error
        401:
          description: Unauthorized
        404:
          description: Driver not found
        500:
          description: Internal server error

    delete:
      tags: [Drivers]
      summary: Delete a driver
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            example: 1
      responses:
        200:
          description: Driver deleted successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  message:
                    type: string
                    example: "Driver deleted successfully"
        401:
          description: Unauthorized
        404:
          description: Driver not found
        500:
          description: Internal server error

  /drivers/license-expiry/{user_id}:
    get:
      tags: [Drivers]
      summary: Get license expiry alerts for a user
      parameters:
        - name: user_id
          in: path
          required: true
          schema:
            type: integer
            example: 1
      responses:
        200:
          description: License expiry alerts retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  data:
                    type: object
                    properties:
                      expiringLicenses:
                        type: array
                        items:
                          type: object
                          properties:
                            id:
                              type: integer
                              example: 1
                            name:
                              type: string
                              example: "John Doe"
                            license_number:
                              type: string
                              example: "DL1234567890"
                            license_expiry:
                              type: string
                              format: date
                              example: "2024-01-15"
                      count:
                        type: integer
                        example: 3
        400:
          description: User ID is required
        401:
          description: Unauthorized
        500:
          description: Internal server error

  /drivers/user/{userId}:
    get:
      tags: [Drivers]
      summary: Get drivers by user ID
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: integer
            example: 1
      responses:
        200:
          description: Drivers for user retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                    example: true
                  data:
                    type: object
                    properties:
                      drivers:
                        type: array
                        items:
                          $ref: '#/components/schemas/DriverWithUser'
                      count:
                        type: integer
                        example: 5
        400:
          description: User ID is required
        401:
          description: Unauthorized
        500:
          description: Internal server error
